apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: argocd-subscription
  annotations:
    apps.open-cluster-management.io/git-branch: rhsc-demo
    apps.open-cluster-management.io/git-path: common/community-argocd-for-apps/templates
    apps.open-cluster-management.io/reconcile-rate: high
  labels:
    app: argocd
    app.kubernetes.io/part-of: argocd
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  channel: rhsc-demo-deviceedge/argocd-channel
  placement:
    placementRef:
      name: argocd-placement
      kind: PlacementRule
posthooks: {}
prehooks: {}
---