tree:
  of: "values"

skupper:
  name: skupper-hub

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

vaultsecret:
  key: secret/data/global/vault-token

job:
  image: registry.connect.redhat.com/hashicorp/vault:1.13.1-ubi