apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    apps.open-cluster-management.io/subscriptions: argocd/argocd-subscription
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - argocd