apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: argocd
  name: argocd-placement
  namespace: argocd
spec:
  clusterSelector:
    matchLabels:
      clusterGroup: deviceedge
