apiVersion: batch/v1
kind: Job
metadata:
  name: secret-converter
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          export AWS_ACCESS_KEY_ID=$(oc get secrets demo -ojsonpath='{.data.AWS_ACCESS_KEY_ID}' | base64 -d)
          export AWS_SECRET_ACCESS_KEY=$(oc get secrets demo -ojsonpath='{.data.AWS_SECRET_ACCESS_KEY}' | base64 -d)
          s3Secret=$(echo "s3.accessKey:$AWS_ACCESS_KEY_ID \ns3.secretKey:$AWS_SECRET_ACCESS_KEY" | base64)
          cat <<EOF | oc apply -f -
          kind: Secret
          apiVersion: v1
          metadata:
            name: odf-secret
            namespace: kafka
          data:
            application.properties: >-
              $s3Secret
            s3Secret: >-
              $s3Secret
          type: Opaque
          EOF
        name: patch-openshift-console
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 400
