apiVersion: batch/v1
kind: Job
metadata:
  name: secret-converter
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          export AWS_ACCESS_KEY_ID=$(oc get secrets -n {{ .Values.s3.bucket.namespace }} demo -ojsonpath='{.data.AWS_ACCESS_KEY_ID}' | base64 -d)
          export AWS_SECRET_ACCESS_KEY=$(oc get secrets demo -n {{ .Values.s3.bucket.namespace }} -ojsonpath='{.data.AWS_SECRET_ACCESS_KEY}' | base64 -d)
          s3Secret=$(echo -e "s3.accessKey:$AWS_ACCESS_KEY_ID\ns3.secretKey:$AWS_SECRET_ACCESS_KEY")
          oc create secret generic odf-secret -n kafka --from-literal=application.properties="$s3Secret" --from-literal=s3Secret="$s3Secret"
        name: patch-openshift-console
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 400
