apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: argocd
  name: argocd-placement
spec:
  clusterSelector:
    matchExpressions:
      - key: clusterGroup
        operator: In
        values:
          - deviceedge
      - key: vendor
        operator: In
        values:
          - MicroShift
      - key: local-cluster
        operator: NotIn
        values:
          - 'true'
---