apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: cluster-argocd
  name: cluster-argocd-placement
spec:
  clusterSelector:
    matchLabels:
      clusterGroup: deviceedge
---