apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cluster-argocd-subscription
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: manifests/install.yaml
    apps.open-cluster-management.io/reconcile-rate: high
  labels:
    app: cluster-argocd
    app.kubernetes.io/part-of: cluster-argocd
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  channel: argocd/cluster-argocd-channel
  placement:
    placementRef:
      name: cluster-argocd-placement
      kind: PlacementRule
posthooks: {}
prehooks: {}
---