secretStore:
  name: vault-backend
  kind: ClusterSecretStore

mqtt:
  broker:
    uri: "tcp://amq-broker-hdls-svc-proxy:61616"
    clientId: "MQTT2KafkaRoute"
    topic: "plc-state"

kafka:
  broker:
    uri: "fog-cluster-kafka-bootstrap:9092"
    topic: "plc-state"