# Hubクラスタのデプロイ用 valuesファイル
# デプロイ先： AWS

global:
  apps:
    namespace: "kafka"
  datacenter:
    storageClassName: gp3-csi
    region: ap-northeast-1
  bucket:
    name: demo
    namespace: openshift-storage

clusterGroup:
  name: hub
  isHubCluster: false

  namespaces:
    - open-cluster-management
    - vault
    - golang-external-secrets
    - kafka
    - openshift-storage
    - multicloud-gitops-with-takebishi-deviceedge

  subscriptions:

    skupper:
      name: skupper-operator
      namespace: openshift-operators
      installPlanApproval: Automatic
      channel: alpha
      source: redhat-operators
      startingCSV: skupper-operator.v1.2

    amq-streams:
      name: amq-streams
      channel: amq-streams-2.4.x
      namespace: openshift-operators

    camel:
      name: red-hat-camel-k
      channel: latest
      namespace: openshift-operators

    odf:
      name: odf-operator
      namespace: openshift-storage
      channel: stable-4.13
      source: redhat-operators
      startingCSV: odf-operator.v4.13.3-rhodf

  projects:
    - hub
    - eso

  applications:

    vault:
      name: vault
      namespace: vault
      project: hub
      path: common/hashicorp-vault

    management-vault-token:
      name: management-vault-token
      namespace: imperative
      project: hub
      path: charts/hub/management-vault-token

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: eso
      path: common/golang-external-secrets

    object-storage:
      name: object-storage
      namespace: openshift-storage
      project: hub
      path: charts/common/object-storage

    skupper:
      name: skupper
      namespace: kafka
      project: hub
      path: charts/hub/skupper

    kafka:
      name: kafka-broker
      namespace: kafka
      project: hub
      path: charts/hub/kafka

    kafdrop:
      name: kafdrop
      namespace: kafka
      project: hub
      path: charts/hub/kafdrop

    mqtt2kafka-plc-state:
      name: mqtt2kafka-plc-state
      namespace: kafka
      project: hub
      path: charts/hub/mqtt2kafka-plc-state

    mqtt2kafka-result:
      name: mqtt2kafka-result
      namespace: kafka
      project: hub
      path: charts/hub/mqtt2kafka-result

    mqtt2kafka-oee:
      name: mqtt2kafka-oee
      namespace: kafka
      project: hub
      path: charts/hub/mqtt2kafka-oee

    # kafka2s3:
    #   name: kafka2s3
    #   namespace: kafka
    #   project: hub
    #   path: charts/hub/kafka2s3

    kafka2s3-plc-state:
      name: kafka2s3-plc-state
      namespace: kafka
      project: hub
      path: charts/hub/kafka2s3-plc-state

    kafka2s3-result:
      name: kafka2s3-result
      namespace: kafka
      project: hub
      path: charts/hub/kafka2s3-result

    kafka2s3-oee:
      name: kafka2s3-oee
      namespace: kafka
      project: hub
      path: charts/hub/kafka2s3-oee

  imperative:
    # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
    # The default schedule is every 10 minutes: imperative.schedule
    # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
    # imagePullPolicy is set to always: imperative.imagePullPolicy
    # For additional overrides that apply to the jobs, please refer to
    # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
    jobs:
    - name: hello-world
      # ansible playbook to be run
      playbook: common/ansible/playbooks/hello-world/hello-world.yaml
      # per playbook timeout in seconds
      timeout: 234
      # verbosity: "-v"