clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
    - open-cluster-management
    - skupper
    - vault
    - golang-external-secrets
    - kafka
    - openshift-storage
    - kafka2s3
    # - config-demo
    # - hello-world

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.7
      #csv: advanced-cluster-management.v2.6.1
    # skupper:
    #   name: skupper-operator
    #   namespace: openshift-operators
    #   installPlanApproval: Automatic
    #   channel: alpha
    #   source: redhat-operators
    #   startingCSV: skupper-operator.v1.2

    amq-streams:
      name: amq-streams
      channel: stable
      namespace: openshift-operators

    camel:
      name: red-hat-camel-k
      channel: latest
      namespace: openshift-operators

    # odf:
    #   name: odf-operator
    #   namespace: openshift-storage
    #   channel: stable-4.13
    #   source: redhat-operators
    #   sourceNamespace: openshift-marketplace

  projects:
    - hub
    # - config-demo
    # - hello-world

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      path: common/acm
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
          - /spec/loggingCA

    vault:
      name: vault
      namespace: vault
      project: hub
      path: common/hashicorp-vault

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      path: common/golang-external-secrets

    # skupper:
    #   name: skupper
    #   namespace: kafka
    #   project: hub
    #   path: charts/hub/skupper

    kafka:
      name: kafka-broker
      namespace: kafka
      project: hub
      path: charts/hub/kafka

    kafdrop:
      name: kafdrop
      namespace: kafka2s3
      project: hub
      path: charts/hub/kafdrop

    camel:
      name: camel
      namespace: kafka2s3
      project: hub
      path: charts/hub/camel

    # object-storage:
    #   name: object-storage
    #   namespace: openshift-storage
    #   project: hub
    #   path: charts/hub/object-storage

    # config-demo:
    #   name: config-demo
    #   namespace: config-demo
    #   project: config-demo
    #   path: charts/all/config-demo

    # hello-world:
    #   name: hello-world
    #   namespace: hello-world
    #   project: hello-world
    #   path: charts/all/hello-world

  imperative:
  #   # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
  #   # The default schedule is every 10 minutes: imperative.schedule
  #   # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
  #   # imagePullPolicy is set to always: imperative.imagePullPolicy
  #   # For additional overrides that apply to the jobs, please refer to
  #   # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
    jobs:
    - name: hello-world
      # ansible playbook to be run
      playbook: common/ansible/playbooks/hello-world/hello-world.yaml
      # per playbook timeout in seconds
      timeout: 234
      # verbosity: "-v"

  managedClusterGroups:
    exampleRegion:
      name: group-one
      acmlabels:
      - name: clusterGroup
        value: group-one
      helmOverrides:
      - name: clusterGroup.isHubCluster
        value: false

      clusterPools:
        exampleAWSPool:
          size: 1
          name: edge-box-group
          openshiftVersion: 4.12.24
          baseDomain: sandbox1282.opentlc.com
          controlPlane:
            count: 1
            platform:
              aws:
                type: m5.2xlarge
          workers:
            count: 0
          platform:
            aws:
              region: ap-northeast-1
          clusters:
          - One
  
      # Before enabling cluster provisioning, ensure AWS and/or Azure
      #   credentials and OCP pull secrets are defined in Vault.
      #   See values-secret.yaml.template
      #
      #clusterPools:
      #  exampleAWSPool:
      #    name: aws-ap
      #    openshiftVersion: 4.10.18
      #    baseDomain: blueprints.rhecoeng.com
      #    platform:
      #      aws:
      #        region: ap-southeast-2
      #    clusters:
      #    - One
      #
      #  exampleAzurePool:
      #    name: azure-us
      #    openshiftVersion: 4.10.18
      #    baseDomain: blueprints.rhecoeng.com
      #    platform:
      #      azure:
      #        baseDomainResourceGroupName: dojo-dns-zones
      #        region: eastus
      #    clusters:
      #    - Two
      #    - Three

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#    pipelines:
#      name: pipelines
#      namespace: production
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: stable
#      overrides:
#      - name: myparam
#        value: myparam
#
#    pipelines_staging:
#    - name: pipelines
#      namespace: staging
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#    vendor-app:
#      name: vendor-app
#      namespace: default
#      project: vendor
#      path: path/to/myapp
#      repoURL: https://github.com/vendor/applications.git
#      targetRevision: main

#  managedSites:
#    factory:
#      name: factory
#      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#      targetRevision: main
#      path: applications/factory
#      helmOverrides:
#      - name: site.isHubCluster
#        value: false
#      clusterSelector:
#        matchExpressions:
#        - key: vendor
#          operator: In
#          values:
#            - OpenShift
