# MicroShiftのデプロイ用 valuesファイル
#
# 付与するクラスタラベル:
# clusterGroup : deviceedge
# vendor: MicroShift
# platform_type: baremetal

global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

# Specify skupper router domain on a fog cluster
skupper:
  connectClusterDomain: apps.demo.sandbox2979.opentlc.com

clusterGroup:
  name: deviceedge
  isHubCluster: false

  namespaces:
    # - golang-external-secrets

    - dgw:
        name: dgw
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged

  # MicroShiftはOLMが未サポートのため利用不可
  subscriptions:
    # amq-broker:
    #   name: amq-broker-rhel8
    #   channel: 7.11.x
    #   namespace: openshift-operators

    # skupper:
    #   name: skupper-operator
    #   namespace: openshift-operators
    #   installPlanApproval: Automatic
    #   channel: alpha
    #   source: redhat-operators
    #   startingCSV: skupper-operator.v1.2

  projects:
    - default

  applications:
    # golang-external-secrets:
    #   name: golang-external-secrets
    #   namespace: golang-external-secrets
    #   project: default
    #   path: charts/deviceedge/golang-external-secrets

    amq:
      name: mqtt-broker
      namespace: dgw
      project: default
      path: charts/deviceedge/amq

    device-gateway:
      name: dgw
      namespace: dgw
      project: default
      path: charts/deviceedge/dgw

    # skupper:
    #   name: skupper
    #   namespace: dgw
    #   project: default
    #   path: charts/deviceedge/skupper

    ### 以下をコメントアウトしてPushするとエッジデバイスにダッシュボードがデプロイされます
    ###
    # dasboard:
    #   name: dashboard
    #   namespace: dgw
    #   project: default
    #   path: charts/common/cps/oee-dashboard/grafana
