# Edgeクラスタのデプロイ用 valuesファイル
#
# 付与するクラスタラベル:
# clusterGroup : edge
# vendor: OpenShift
# platform_type: baremetal

global:
  hubClusterDomain: apps.demo.sandbox1326.opentlc.com
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  datacenter:
    # storageClassName: gp3-csi
    storageClassName: lvms-vg1
    region: fog

skupper:
  # connectClusterDomain: apps.demo.sandbox3027.opentlc.com
  connectClusterDomain: apps.fog.rhsc.local

clusterGroup:
  name: edge
  isHubCluster: false

  namespaces:
    - golang-external-secrets
    - dgw

  subscriptions:
    amq-broker:
      name: amq-broker-rhel8
      channel: 7.11.x
      namespace: openshift-operators

    # amq-streams:
    #   name: amq-streams
    #   channel: stable
    #   namespace: openshift-operators

    # camel:
    #   name: red-hat-camel-k
    #   channel: latest
    #   namespace: openshift-operators

    # odf:
    #   name: odf-operator
    #   namespace: openshift-storage
    #   channel: stable-4.12
    #   source: redhat-operators
    #   startingCSV: odf-operator.v4.12.5-rhodf

    skupper:
      name: skupper-operator
      namespace: openshift-operators
      installPlanApproval: Automatic
      channel: alpha
      source: redhat-operators
      startingCSV: skupper-operator.v1.2

  projects:
    - eso
    - dw-gateway
    - cps
    # - edge-data-pipeline

  applications:

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: eso
      path: charts/deviceedge/golang-external-secrets

    # golang-external-secrets:
    #   name: golang-external-secrets
    #   namespace: golang-external-secrets
    #   project: eso
    #   path: common/golang-external-secrets

    amq:
      name: mqtt-broker
      namespace: dgw
      project: dw-gateway
      path: charts/edge/amq

    device-gateway:
      name: dgw
      namespace: dgw
      project: dw-gateway
      path: charts/edge/dgw

    skupper:
      name: skupper
      namespace: dgw
      project: dw-gateway
      path: charts/edge/skupper

    ledblink:
      name: ledblink
      namespace: dgw
      project: cps
      path: charts/common/cps/ledblink-monitor

    model-gen:
      name: model-gen
      namespace: dgw
      project: cps
      path: charts/common/cps/model_gen

    model-get:
      name: model-get
      namespace: dgw
      project: cps
      path: charts/common/cps/model_get

    # nginx-rtmp:
    #   name: nginx-rtmp
    #   namespace: dgw
    #   project: cps
    #   path: charts/common/nginx-rtmp

    oee:
      name: oee
      namespace: dgw
      project: cps
      path: charts/common/cps/oee-dashboard/oee-handler

    dasboard:
      name: dashboard
      namespace: dgw
      project: cps
      path: charts/common/cps/oee-dashboard/grafana

    quality:
      name: quality
      namespace: dgw
      project: cps
      path: charts/common/cps/quality-handler

    # mqtt2kafka:
    #   name: mqtt2kafka
    #   namespace: kafka
    #   project: edge-data-pipeline
    #   path: charts/fog/mqtt2kafka

    # kafka2s3:
    #   name: kafka2s3
    #   namespace: kafka
    #   project: edge-data-pipeline
    #   path: charts/fog/kafka2s3

    # kafka:
    #   name: kafka-broker
    #   namespace: kafka
    #   project: edge-data-pipeline
    #   path: charts/fog/kafka

    # kafka-mirror:
    #   name: kafka-mirror
    #   namespace: kafka
    #   project: edge-data-pipeline
    #   path: charts/fog/kafka-mirror-maker

    # kafdrop:
    #   name: kafdrop
    #   namespace: kafka
    #   project: edge-data-pipeline
    #   path: charts/fog/kafdrop

    # skuppe-fog:
    #   name: skupper-fog
    #   namespace: kafka
    #   project: edge-data-pipeline
    #   path: charts/fog/skupper

    # クラウド上のクラスタは以下をコメントアウト
    # golang-external-secrets:
    #   name: golang-external-secrets
    #   namespace: golang-external-secrets
    #   project: eso
    #   path: common/golang-external-secrets


    # object-storage:
    #   name: object-storage
    #   namespace: openshift-storage
    #   project: fog
    #   path: charts/common/object-storage

    # mqtt2kafka-plc-state:
    #   name: mqtt2kafka-plc-state
    #   namespace: kafka
    #   project: fog
    #   path: charts/fog/mqtt2kafka-plc-state

    # mqtt2kafka-result:
    #   name: mqtt2kafka-result
    #   namespace: kafka
    #   project: fog
    #   path: charts/fog/mqtt2kafka-result

    # mqtt2kafka-oee:
    #   name: mqtt2kafka-oee
    #   namespace: kafka
    #   project: fog
    #   path: charts/fog/mqtt2kafka-oee

    # kafka2s3-plc-state:
    #   name: kafka2s3-plc-state
    #   namespace: kafka
    #   project: fog
    #   path: charts/fog/kafka2s3-plc-state

    # kafka2s3-result:
    #   name: kafka2s3-result
    #   namespace: kafka
    #   project: fog
    #   path: charts/fog/kafka2s3-result

    # kafka2s3-oee:
    #   name: kafka2s3-oee
    #   namespace: kafka
    #   project: fog
    #   path: charts/fog/kafka2s3-oee

    # kafka:
    #   name: kafka-broker
    #   namespace: kafka
    #   project: fog
    #   path: charts/fog/kafka

    # kafka-mirror-plc-state:
    #   name: kafka-mirror-plc-state
    #   namespace: kafka
    #   project: fog
    #   path: charts/fog/kafka-mirror-maker-plc-state

    # kafka-mirror-result:
    #   name: kafka-mirror-result
    #   namespace: kafka
    #   project: fog
    #   path: charts/fog/kafka-mirror-maker-result

    # kafka-mirror-oee:
    #   name: kafka-mirror-oee
    #   namespace: kafka
    #   project: fog
    #   path: charts/fog/kafka-mirror-maker-oee

    # kafdrop:
    #   name: kafdrop
    #   namespace: kafka
    #   project: fog
    #   path: charts/fog/kafdrop

    # skupper:
    #   name: skupper
    #   namespace: kafka
    #   project: fog
    #   path: charts/fog/skupper