# Edgeクラスタのデプロイ用 valuesファイル
#
# 付与するクラスタラベル:
# clusterGroup : edge
# vendor: OpenShift
# platform_type: baremetal

global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

skupper:
  connectClusterDomain: apps.fog.rhsc.local

clusterGroup:
  name: edge
  isHubCluster: false

  namespaces:
    - golang-external-secrets
    - dgw
    - mqtt

  subscriptions:
    amq-broker:
      name: amq-broker-rhel8
      channel: 7.11.x
      namespace: openshift-operators

    # amq-streams:
    #   name: amq-streams
    #   channel: stable
    #   namespace: openshift-operators

    # camel:
    #   name: red-hat-camel-k
    #   channel: latest
    #   namespace: openshift-operators

    # odf:
    #   name: odf-operator
    #   namespace: openshift-storage
    #   channel: stable-4.12
    #   source: redhat-operators
    #   startingCSV: odf-operator.v4.12.5-rhodf

    skupper:
      name: skupper-operator
      namespace: openshift-operators
      installPlanApproval: Automatic
      channel: alpha
      source: redhat-operators
      startingCSV: skupper-operator.v1.2

  projects:
    - eso
    - dw-gateway
    - cps
    # - edge-data-pipeline

  applications:

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: default
      path: charts/deviceedge/golang-external-secrets

    amq:
      name: mqtt-broker
      namespace: mqtt
      project: dw-gateway
      path: charts/edge/amq

    device-gateway:
      name: dgw
      namespace: dgw
      project: dw-gateway
      path: charts/edge/dgw

    skupper:
      name: skupper
      namespace: mqtt
      project: dw-gateway
      path: charts/edge/skupper

    ledblink:
      name: ledblink
      namespace: dgw
      project: cps
      path: charts/common/ledblink-monitor

    model_gen:
      name: model_gen
      namespace: dgw
      project: cps
      path: charts/common/model_gen

    model_get:
      name: model_gen
      namespace: dgw
      project: cps
      path: charts/common/model_get

    # nginx-rtmp:
    #   name: nginx-rtmp
    #   namespace: dgw
    #   project: cps
    #   path: charts/common/nginx-rtmp

    oee:
      name: oee
      namespace: dgw
      project: cps
      path: charts/common/oee-dashboard/oee-handler

    dasboard:
      name: dashboard
      namespace: dgw
      project: cps
      path: charts/common/oee-dashboard/grafana

    quality:
      name: quality
      namespace: dgw
      project: cps
      path: charts/common/quality-handler

    # mqtt2kafka:
    #   name: mqtt2kafka
    #   namespace: kafka
    #   project: edge-data-pipeline
    #   path: charts/fog/mqtt2kafka

    # kafka2s3:
    #   name: kafka2s3
    #   namespace: kafka
    #   project: edge-data-pipeline
    #   path: charts/fog/kafka2s3

    # kafka:
    #   name: kafka-broker
    #   namespace: kafka
    #   project: edge-data-pipeline
    #   path: charts/fog/kafka

    # kafka-mirror:
    #   name: kafka-mirror
    #   namespace: kafka
    #   project: edge-data-pipeline
    #   path: charts/fog/kafka-mirror-maker

    # kafdrop:
    #   name: kafdrop
    #   namespace: kafka
    #   project: edge-data-pipeline
    #   path: charts/fog/kafdrop

    # skuppe-fog:
    #   name: skupper-fog
    #   namespace: kafka
    #   project: edge-data-pipeline
    #   path: charts/fog/skupper
