{{- if .Values.storageSystem.deploy }}
apiVersion: odf.openshift.io/v1alpha1
kind: StorageSystem
metadata:
  finalizers:
  - storagesystem.odf.openshift.io
  name: {{ .Values.storageSystem.name }}
  namespace: {{ .Values.storageSystem.namespace }}
spec:
  kind: {{ .Values.storageSystem.spec.kind }}
  name: {{ .Values.storageSystem.spec.name }}
  namespace: {{ default .Values.storageSystem.namespace  .Values.storageSystem.spec.namespace }}
{{- end }}
