apiVersion: v1
kind: Service
metadata:
  name: argocd-server
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
    nodePort: 32000
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort