global:
  apps:
    namespace: "kafka"
  datacenter:
    storageClassName: gp3-csi
    region: ap-northeast-2
  bucket:
    name: demo

odf:
  namespace: openshift-storage
  serviceUrl: "http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local"
  externalUrl: "https://s3-rgw-openshift-storage"
  targetBucket: com.redhat.demo
  mon:
    requests:
       cpu: 1
       memory: 2Gi
  mds:
    requests:
      cpu: 3
      memory: 8Gi
  mgr:
    requests:
      cpu: 1
      memory: 3Gi
  noobaacore:
    requests:
      cpu: 1
      memory: 4Gi
  noobaadb:
    requests:
      cpu: 1
      memory: 4Gi
  osd:
    requests:
      cpu: 2
      memory: 5Gi
    pvc:
      storage: 500Gi
  storageClass:
    name: ocs-storagecluster-ceph-rgw
    objectStoreName: ocs-storagecluster-cephobjectstore

route:
  name: s3-rgw
  service:
    name: rook-ceph-rgw-ocs-storagecluster-cephobjectstore
    weight: 100
  port:
    targetPort: http

toolbox:
  name: ocsinit
  enableCephTools: true

#Define the odf storageSystem parameters
storageSystem:
  deploy: false
  name: ocs-storagecluster-storagesystem
  namespace: openshift-storage
  spec:
    kind: storagecluster.ocs.openshift.io/v1
    name: ocs-storagecluster
    namespace: ""

#RoleBasedAccessControl
#RoleBasedAccessControl
serviceAccountName: odf-patch-sa
rbac:
  roles:
    - name: odf-patch-role
      createRole: true
      apiGroups:
        - '""'
        - 'operator.openshift.io'
      scope:
        cluster: true
      resources:
        - nodes
        - consoles
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
  roleBindings:
    - name: odf-patch-rolebinding
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: odf-patch-sa
        namespace: openshift-storage
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: odf-patch-role

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
