apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafdrop.fullname" . }}
  labels:
    {{- include "kafdrop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kafdrop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kafdrop.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "kafdrop.fullname" . }}-sa
      containers:
        - name: {{ .Chart.Name }}
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
        {{- toYaml . | nindent 8 }}
        {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: KAFKA_BROKERCONNECT
              value: {{ .Values.kafka.bootstrapServers }}
            - name: SCHEMAREGISTRY_CONNECT
              value: {{ include "kafdrop.schema-registry.url" . | quote }}
            - name: JVM_OPTS
              value: "{{ .Values.heapOpts }} -Dlog4j2.formatMsgNoLookups=true"
            {{- if .Values.kerberos.enabled }}
            - name: KAFKA_PROPERTIES_FILE
              value: /etc/kafka/kafka.properties
            {{- end }}
            - name: CMD_ARGS
              value: "{{ .Values.cmdArgs }}"
          ports:
            - name: tcp
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: tcp
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: tcp
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          volumeMounts:
          - name: tmp
            mountPath: /tmp
          {{- if .Values.kerberos.enabled }}
          - name: keytabs
            mountPath: /keytabs
            readOnly: true
          - name: krb5
            mountPath: /etc/krb5.conf
            subPath: krb5.conf
          - name: kafka-properties
            mountPath: /etc/kafka/
            readOnly: true
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: tmp
        emptyDir: {}
      {{- if .Values.kerberos.enabled }}
      - name: krb5
        configMap:
          name: {{ required "The .Values.kerberos.krb5Conf is required when kerberos enabled!" .Values.kerberos.krb5Conf }}
      - name: keytabs
        secret:
          secretName: {{ required "The .Values.kerberos.keyTabSecret is required when kerberos enabled!" .Values.kerberos.keyTabSecret }}
      - name: kafka-properties
        configMap:
          name: {{ include "kafdrop.fullname" . }}
      {{- end }}