apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafdrop.fullname" . }}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kafdrop.fullname" . }}-sa-clusterrole
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafdrop.fullname" . }}-sa-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kafdrop.fullname" . }}-sa-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "kafdrop.fullname" . }}-sa
