apiVersion: batch/v1
kind: Job
metadata:
  name: vault-secret-create
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - image: {{ .Values.image }}
        command:
        - /bin/bash
        - -c
        - |
          VAULT_TOKEN=$(cat vault_data_json/vault_data_json | grep root_token | sed -e "s/\"root_token\": \"\(.*\)\",/\1/" | sed "s/ //g")
          oc delete secret vault-token
          oc create secret generic vault-token --from-literal=token="$VAULT_TOKEN"
        name: patch-secret-creator
        volumeMounts:
        - mountPath: vault_data_json
          readOnly: true
          name: vaultkeys
      volumes:
      - name: vaultkeys
        secret:
          secretName: vaultkeys
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 400
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
