apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: expose-service-patch
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          curl https://raw.githubusercontent.com/yd-ono/multicloud-gitops-with-takebishi/main/common/scripts/get-skupper.sh | sh
          if [[ `skupper -n kafka service status | grep "No services defined" ` ]]; then
            oc -n kafka annotate service hub-cluster-kafka-0 skupper.io/proxy=tcp
            oc -n kafka annotate service hub-cluster-kafka-1 skupper.io/proxy=tcp
            oc -n kafka annotate service hub-cluster-kafka-2 skupper.io/proxy=tcp
            skupper -n kafka expose service hub-cluster-kafka-bootstrap --address hub-cluster-kafka-bootstrap-ex --protocol tcp
          else
            exit 0
          fi
        name: expose-service-patch
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 400
