---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: vault-secret
  namespace: kafka
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: vault-secret
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.vaultsecret.key }}