{{- $VAULT_TOKEN := printf "{{ cat `VAULT_TOKEN:` .vaulttoken }}" }}
{{- range .Values.namespaces }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: vault-token-secret
  namespace: {{ . }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: vault-token-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data: "{{ $VAULT_TOKEN }}"
  data:
    - secretKey: "vaulttoken"
      remoteRef:
        key: {{ $.Values.vaultsecret.key }}
        property: VAULT_TOKEN
{{- end }}