apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: upload-skupper-token-to-vault
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          export VAULT_SKIP_VERIFY=true
          export VAULT_ADDR=https://vault-vault.{{ .Values.global.hubClusterDomain }}
          export VAULT_TOKEN=$content
          vault login
        name: patch-openshift-console
        envFrom:
        - secretRef:
            name: vault-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 400
