apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  name: upload-vault-token
  namespace: imperative
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          VAULT_TOKEN=$(cat vault_data_json/vault_data_json | grep root_token | sed -e "s/\"root_token\": \"\(.*\)\",/\1/")
          vault login token="$VAULT_TOKEN"
          vault kv put secret/global/vault-token VAULT_TOKEN="$VAULT_TOKEN"
        name: upload-vault-token
        env:
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: VAULT_ADDR
          value: "https://vault-vault.{{ .Values.global.hubClusterDomain }}"
        volumeMounts:
        - mountPath: vault_data_json
          readOnly: true
          name: vaultkeys
      volumes:
      - name: vaultkeys
        secret:
          secretName: vaultkeys
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 400
