apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: upload-skupper-token-to-vault
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          vault login
        name: upload-skupper-token-to-vault
        env:
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: VAULT_ADDR
          value: "https://vault-vault.{{ .Values.global.hubClusterDomain }}"
        envFrom:
        - secretRef:
            name: VAULT_TOKEN
            key: content
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 400
