apiVersion: batch/v1
kind: Job
metadata:
  name: upload-skupper-token-to-vault
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          CACRT=$(oc -n kafka get secret {{ .Values.skupper.token.name }} -ojsonpath="{.data.ca\.crt}")
          TLSCRT=$(oc -n kafka get secret {{ .Values.skupper.token.name }} -ojsonpath="{.data.tls\.crt}")
          TLSKEY=$(oc -n kafka get secret {{ .Values.skupper.token.name }} -ojsonpath="{.data.tls\.key}")
          VAULT_TOKEN=$(cat vault_data_json/vault_data_json | grep root_token | sed -e "s/\"root_token\": \"\(.*\)\",/\1/")
          vault login token="$VAULT_TOKEN"
          vault kv put secret/global/skupper-hub-token ca.crt="$CACRT"
          vault kv put secret/global/skupper-hub-token tls.crt="$TLSCRT"
          vault kv put secret/global/skupper-hub-token tls.key="$TLSKEY"
        name: upload-skupper-token-to-vault
        env:
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: VAULT_ADDR
          value: "https://vault-vault.{{ .Values.global.hubClusterDomain }}"
        envFrom:
        - secretRef:
            name: vault-token
            key: VAULT_TOKEN
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 400
