kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.ignoreDifferences.build.openshift.io_BuildConfig: |
    jsonPointers:
    - /status/lastVersion
