apiVersion: v1
kind: ConfigMap
metadata:
  name: model-gen-config
  namespace: cps
data:
  VIDEO_ADDRESS: '/dev/video0'
  MODEL_ADDRESS: 'http://model-get:8000'
  RECT_HEIGHT: '30'
  RECT_WIDTH: '30'
  POS0: '{"x": 452 , "y": 105}'
  POS1: '{"x": 305 , "y": 138}'
  POS2: '{"x": 136 , "y": 176}'
  POS3: '{"x": 443 , "y": 175}'
  POS4: '{"x": 314 , "y": 205}'
  POS5: '{"x": 167 , "y": 238}'
  POS6: '{"x": 432 , "y": 231}'
  POS7: '{"x": 315 , "y": 259}'
  POS8: '{"x": 189 , "y": 293}'
  DEBUG: 'False'