tree:
  of: "values"

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

hubkafka:
  uri: "hub-cluster-kafka-bootstrap-ex:9092"
  topic: "dgw"

edgekafka:
  uri: "fog-cluster-kafka-bootstrap:9092"
  topic: "dgw"

mirror:
  replicas: 1
  topicsPattern: .*
  groupsPattern: .*