apiVersion: v1
kind: ConfigMap
metadata:
  name: skupper-site
  namespace: {{ . }}
data:
  cluster-local: "false"
  console: "true"
  console-authentication: internal
  edge: "false"
  name: deviceedge
  router-console: "true"
  service-controller: "true"
  service-sync: "true"