apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: job-console-update
  namespace: {{ .Values.odf.namespace }}
spec:
  template:
  backoffLimit: 1
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          oc patch console.operator cluster -n openshift-storage --type json -p '[{"op": "add", "path": "/spec/plugins/0", "value": "odf-console"}]'
        name: patch-openshift-console
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 400
