apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: demo
  namespace: openshift-storage
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  bucketName: demo
  generateBucketName: demo
  objectBucketName: obc-openshift-storage-demo
  storageClassName: openshift-storage.noobaa.io
