apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: golang-external-secrets
spec:
  provider:
    vault:
      server: https://vault-vault.{{ .Values.global.hubClusterDomain }}
      path: secret
      # Version of KV backend
      version: v2
      auth:
        tokenSecretRef:
          key: token
          name: vault-token
