apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-to-s3-config
data:
  application.properties: |

    kafka.broker.uri={{ .Values.kafka.broker.uri }}
    kafka.broker.topic={{ .Values.kafka.broker.topic }}

    s3.region={{ .Values.global.s3.bucket.region }}
    s3.bucket.name={{ .Values.global.s3.bucket.name }}
    s3.message.aggregation.count={{ .Values.global.s3.bucket.message.aggregation.count }}
    s3.custom.endpoint.enabled={{ .Values.global.s3.bucket.custom.endpoint.enabled }}
    s3.custom.endpoint.url=s3.openshift-storage.svc