apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  annotations:
    camel.apache.org/operator.id: camel-k
  name: kafka2s3
spec:
  configuration:
    - type: configmap
      value: kafka-to-s3-config
    - type: secret
      value: s3-secret
  flows:
    - route:
        id: route-kafka-to-s3
        from:
          id: from-kafka-{{ $.Values.kafka.broker.topic }}
          uri: kafka:{{ $.Values.kafka.broker.topic}}
          parameters:
            brokers: {{ $.Values.kafka.broker.uri }}
          steps:
            - to:
                id: to-s3
                uri: 'kamelet:aws-s3-streaming-upload-sink'
                parameters:
                  bucketNameOrArn: {{ $.Values.global.s3.bucket.name }}
                  keyName: {{ $.Values.global.s3.bucket.key_name }}
                  region: {{ $.Values.global.s3.bucket.region }}
                  autoCreateBucket: true
                  batchMessageNumber: 10
                  batchSize: 1
                  streamingUploadTimeout: 1
                  useDefaultCredentialsProvider: true
  traits: {}