# For use when manually creating clusters with ACM
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-external-secret
spec: 
  data:
  - secretKey: awsKeyId
    remoteRef:
      key: {{ default "secret/hub/aws" .awsKeyPath }}
      property: aws_access_key_id
  - secretKey: awsAccessKey
    remoteRef:
      key: {{ default "secret/hub/aws" .awsKeyPath }}
      property: aws_secret_access_key
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: s3-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        s3.accessKey: |-
          {{ "{{ .awsKeyId | toString }}" }}
        s3.secretKey: |-
          {{ "{{ .awsAccessKey | toString }}" }}