{{- range .Values.clusterGroup.applications.deviceedge_argocd }}
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    apps.open-cluster-management.io/subscriptions: {{ .name }}/{{ .name }}-subscription
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - argocd
---
{{- end }}