apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: {{ .name }}-channel
  namespace: {{ .namespace }}-channel
spec:
  pathname: https://github.com/yd-ono/multicloud-gitops-with-takebishi
  type: Git
---
