apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: argocd
  name: {{ .Values.clusterGroup.applications.name }}-placement
  namespace: {{ .Values.clusterGroup.applications.namespace }}
spec:
  clusterSelector:
    matchLabels:
      clusterGroup: deviceedge
---