apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: {{ .name }}-subscription
  namespace: {{ .namespace }}
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: common/community-argocd/templates
  labels:
    app: argocd
    app.kubernetes.io/part-of: argocd
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  channel: {{ .namespace }}-channel/{{ .name }}-channel
  placement:
    placementRef:
      name: argocd-placement
      kind: PlacementRule
posthooks: {}
prehooks: {}
---