tree:
  of: "values"

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

mqtt:
  name: amq-broker
  image: registry.redhat.io/amq7/amq-broker-rhel8:7.11.1-2.1689584940
  port: 61616
  size: 1