apiVersion: v1
kind: Service
metadata:
  labels:
    app: amq-broker
  name: amq-web
  namespace: amq-broker
spec:
  ports:
  - port: 8161
    protocol: TCP
    targetPort: 8161
  selector:
    app:  amq-broker
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: amq-broker
  name: amqp
  namespace: amq-broker
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app:  amq-broker
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: amq-broker-mqtt
  name: amqp-mqtt
  namespace: amq-broker
spec:
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app:  amq-broker
  sessionAffinity: None
  type: NodePort