kind: Service
apiVersion: v1
metadata:
  name: mqtt
spec:
  ports:
    - name: amq-broker-hdls-svc-proxy8161
      protocol: TCP
      port: 8161
      targetPort: 8161
    - name: amq-broker-hdls-svc-proxy61616
      protocol: TCP
      port: 61616
      targetPort: 61616
      nodePort: 32000
  type: NodePort
  selector:
    app: amq-broker