[whitelist]
# As of v4, gitleaks only matches against filename, not path in the
# files directive.  Leaving content for backwards compatibility.
files = [
  "ansible/plugins/modules/*.py",
  "ansible/tests/unit/test_*.py",
  "ansible/tests/unit/*.yaml",
]

[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore anything with the word funkymonkey anywhere in the path
    '''DeviceGateway.lic''',
  ]