global:
  localClusterDomain: svc

  s3:
    bucket:
      name: demo
      uri: http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc
      namespace: openshift-storage
      region: ap-northeast-1
      key_name: kafka.txt
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: true

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

s3secret:
  key: secret/data/odf/aws
  namespaces: kafka

kafka:
  broker:
    uri: "hub-cluster-kafka-bootstrap-ex:9092"
    topic: "edge-kafka-cluster.dgw"