global:
  localClusterDomain: svc

  s3:
    bucket:
      name: demo-w5qtp-image-registry-ap-northeast-1-wbalepgseoxswqjkuyaig
      region: ap-northeast-1
      key_name: kafka.txt
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

s3secret:
  key: secret/hub/aws
  namespaces:
    - kafka

kafka:
  broker:
    uri: "hub-cluster-kafka-bootstrap.broker.svc.cluster.local:9092"
    topic: "dgw"