global:
  localClusterDomain: svc

  s3:
    bucket:
      name: demo
      region: us-east-2
      key_name: kafka.txt
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

s3secret:
  key: secret/data/hub/aws
  namespaces:
    - kafka

kafka:
  broker:
    uri: "hub-cluster-kafka-bootstrap.broker:9092"
    topic: "dgw"