tree:
  of: "values"

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

mqtt:
  broker:
    uri: "tcp://amq-broker-hdls-svc:61616"
    clientId: "MQTT2KafkaRoute"
    topic: "dgw"

kafka:
  broker:
    uri: "fog-cluster-kafka-bootstrap:9092"
    topic: "dgw"