global:
  localClusterDomain: svc

  s3:
    bucket:
      name: demo
      region: ap-northeast-1
      key_name: kafka.txt
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: true

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

kafka:
  broker:
    uri: "hub-cluster-kafka-bootstrap.broker.svc.cluster.local:9092"
    topic: "dgw"