global:
  localClusterDomain: svc

  s3:
    bucket:
      name: demo
      region: ap-northeast-1
      key_name: kafka.txt
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: true

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

s3secret:
  key: secret/hub/aws
  namespaces:
    - kafka

kafka:
  broker:
    uri: "fog-cluster-kafka-bootstrap:9092"
    topic: "dgw"