global:
  localClusterDomain: svc

  s3:
    bucket:
      name: BUCKETNAME
      region: AWSREGION
      key_name: kafka.txt
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

s3secret:
  key: secret/data/global/odf
  namespaces:
    - kafka

kafka:
  broker:
    uri: "fog-cluster-kafka-bootstrap:9092"
    topic: "dgw"