global:
  localClusterDomain: svc

  s3:
    bucket:
      name: demo
      uri: http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc
      namespace: openshift-storage
      region: ap-northeast-3
      key_name: kafka.txt
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: true

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

s3secret:
  key: secret/data/odf/aws
  namespaces: kafka

kafka:
  broker:
    uri: "fog-cluster-kafka-bootstrap:9092"
    topic: "dgw"

serviceAccountName: secret-converter-sa
rbac:
  roles:
    - name: secret-converter-role
      createRole: true
      apiGroups:
        - '""'
      scope:
        cluster: true
      resources:
        - secrets
      verbs:
        - "get"
        - "list"
        - "create"
        - "delete"
  roleBindings:
    - name: secret-converter-rolebinding
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: secret-converter-sa
        namespace: kafka
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: secret-converter-role

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest