{{- $CACRT := printf "{{ cat .cacrt }}" }}
{{- $TLSCRT := printf "{{ cat .tlscrt }}" }}
{{- $TLSKEY := printf "{{ cat .tlskey }}" }}
{{- range .Values.namespaces }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: to-hub
  namespace: {{ . }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: to-hub
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        "ca.crt": "{{ $CACRT }}"
        "tls.crt": "{{ $TLSCRT }}"
        "tls.key": "{{ $TLSKEY }}"
  data:
    - secretKey: "ca.crt"
      remoteRef:
        key: {{ $.Values.skuppertoken.key }}
        property: ca.crt
    - secretKey: "tls.crt"
      remoteRef:
        key: {{ $.Values.skuppertoken.key }}
        property: tls.crt
    - secretKey: "tls.key"
      remoteRef:
        key: {{ $.Values.skuppertoken.key }}
        property: tls.key
{{- end }}