apiVersion: v1
kind: ConfigMap
metadata:
  name: skupper-site
data:
  name: edge-site
  console: "true"
  console-user: "admin"
  console-authentication: "openshift"
  console-password: "admin"
  flow-collector: "true"