kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: akhq
spec:
  path: /
  to:
    kind: Service
    name: akhq
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None