apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  kafka:
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        # configuration:
        #   brokers:
        #     - broker: 0
        #       advertisedHost: hub-cluster-kafka-0.hub-cluster-kafka-brokers
        #     - broker: 1
        #       advertisedHost: hub-cluster-kafka-1.hub-cluster-kafka-brokers
        #     - broker: 2
        #       advertisedHost: hub-cluster-kafka-2.hub-cluster-kafka-brokers
      - name: plain2
        port: 9094
        type: internal
        tls: false
        # configuration:
        #   brokers:
        #     - broker: 0
        #       advertisedHost: hub-cluster-kafka-0.hub-cluster-kafka-brokers
        #     - broker: 1
        #       advertisedHost: hub-cluster-kafka-1.hub-cluster-kafka-brokers
        #     - broker: 2
        #       advertisedHost: hub-cluster-kafka-2.hub-cluster-kafka-brokers
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}