apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  kafka:
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          bootstrap:
            annotations:
              skupper.io/address: hub-cluster-kafka-bootstrap
              skupper.io/port: 9092
              skupper.io/proxy: tcp
          brokers:
            - broker: 0
                annotations:
                  skupper.io/address: hub-cluster-kafka-brokers
                  skupper.io/port: 9092
                  skupper.io/proxy: tcp
            - broker: 1
                annotations:
                  skupper.io/address: hub-cluster-kafka-brokers
                  skupper.io/port: 9092
                  skupper.io/proxy: tcp
            - broker: 2
                annotations:
                  skupper.io/address: hub-cluster-kafka-brokers
                  skupper.io/port: 9092
                  skupper.io/proxy: tcp
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: kafdrop
        port: 9094
        tls: false
        type: internal
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}