apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  kafka:
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: cluster-ip
        tls: false
        configuration:
          bootstrap:
            annotations:
              skupper.io/address: hub-cluster-kafka-bootstrap
              skupper.io/proxy: tcp
          brokers:
            - broker: 0
              advertisedHost: hub-cluster-kafka-0
            - broker: 1
              advertisedHost: hub-cluster-kafka-1
            - broker: 2
              advertisedHost: hub-cluster-kafka-2
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}