apiVersion: v1
kind: ConfigMap
metadata:
  name: model-gen-config
data:
  VIDEO_ADDRESS: '/dev/video0'
  MODEL_ADDRESS: 'http://model-get:8000'
  RECT_HEIGHT: '30'
  RECT_WIDTH: '30'
  # POS0: '{"x": 136 , "y": 135}'
  # POS1: '{"x": 315 , "y": 136}'
  # POS2: '{"x": 473 , "y": 135}'
  # POS3: '{"x": 150 , "y": 205}'
  # POS4: '{"x": 306 , "y": 202}'
  # POS5: '{"x": 443 , "y": 201}'
  # POS6: '{"x": 159 , "y": 263}'
  # POS7: '{"x": 298 , "y": 256}'
  # POS8: '{"x": 419 , "y": 252}'
  POS0: '{"x": 363 , "y": 111}'
  POS1: '{"x": 242 , "y": 148}'
  POS2: '{"x": 90 , "y": 186}'
  POS3: '{"x": 361 , "y": 172}'
  POS4: '{"x": 253 , "y": 203}'
  POS5: '{"x": 113 , "y": 249}'
  POS6: '{"x": 350 , "y": 224}'
  POS7: '{"x": 250 , "y": 259}'
  POS8: '{"x": 127 , "y": 303}'
  DEBUG: 'False'