secretStore:
  name: vault-backend
  kind: ClusterSecretStore

dgw:
  storageclass: gp3-csi
  setting:
    mqttServer: amq-broker-hdls-svc:61616
    clientID: dgw
    destinationTopic: dgw

dgwtoken:
  key: secret/data/global/dgw