apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-console
secrets:
- name: openshift-console-token
---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-console-secret
  annotations:
    kubernetes.io/service-account.name: openshift-console
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-console-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: openshift-console