apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: job-console-update
  namespace: {{ .Values.odf.namespace }}
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          if [[ `oc get console.operator cluster -n openshift-storage -ojsonpath='{.spec.plugins}'` ]]
          then
            oc patch console.operator cluster -n openshift-storage --type json -p '[{"op": "add", "path": "/spec/plugins/0", "value": "odf-console"}]'
          else
            oc patch console.operator cluster -n openshift-storage --type json -p '[{"op": "add", "path": "/spec/plugins", "value": ["odf-console"]}]'
          fi
        name: patch-openshift-console
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 400
