apiVersion: batch/v1
kind: Job
metadata:
  name: secret-converter
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          s3Secret=$(echo -e "s3.accessKey:$AWS_ACCESS_KEY_ID\ns3.secretKey:$AWS_SECRET_ACCESS_KEY")
          oc delete secret odf-secret -n {{ .Values.s3secret.namespaces }}
          oc create secret generic odf-secret -n {{ .Values.s3secret.namespaces }} --from-literal=application.properties="$s3Secret" --from-literal=s3Secret="$s3Secret"
        name: patch-secret-converter
        envFrom:
        - secretRef:
            name: demo
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 400
