kind: Service
apiVersion: v1
metadata:
  name: model-get
  labels:
    app: model-get
spec:
  type: NodePort
  ports:
    - name: 8000-tcp
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31000
  selector:
    app: model-get