global:
  localClusterDomain: svc

  s3:
    bucket:
      name: demo-32003d6d-a310-46f1-84db-30981901a699
      uri: http://s3.openshift-storage.svc.cluster.local
      namespace: kafka
      region: fog
      key_name: kafka.txt
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: true

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

s3secret:
  key: secret/data/odf/aws
  namespaces: kafka

kafka:
  broker:
    uri: "fog-cluster-kafka-bootstrap:9092"
    topic: "result"